apiVersion: apps/v1
kind: Deployment
metadata:

  name: argo-cd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-cd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-cd
    spec:
      containers:
      - image: nginx
        name: nginx
